In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler

In [3]:
df = pd.read_csv('données_enregistrées.csv')
print("DataFrame original:")
print(df)

DataFrame original:
         ID  Salaire  Age  Expérience (années)  Taille (cm)
0   ID00001    34578   22                    2          188
1   ID00002    38485   25                    5          190
2   ID00003    36556   25                    4          167
3   ID00004    31544   31                    1          165
4   ID00005    60860   41                   20          154
5   ID00006    40284   43                    6          191
6   ID00007    49904   58                   16          192
7   ID00008    48416   45                   16          181
8   ID00009    31675   28                    1          151
9   ID00010    58690   46                   19          151
10  ID00011    39932   46                    4          189
11  ID00012    46938   34                    9          191
12  ID00013    34414   23                    2          185
13  ID00014    50560   45                   20          188
14  ID00015    66040   46                   20          161
15  ID00016    52560   39                   20          196
16  ID00017    46920   59                   15          168
17  ID00018    53648   47                    8          177
18  ID00019    32077   35                    1          150
19  ID00020    35850   30                    2          164

In [5]:
features = ['Salaire', 'Age', 'Expérience (années)', 'Taille (cm)']

In [7]:
normalisation = MinMaxScaler()
df_norm = pd.DataFrame(normalisation.fit_transform(df[features]), columns=[features])
print(df_norm)

     Salaire       Age Expérience (années) Taille (cm)
0   0.087952  0.000000            0.052632    0.826087
1   0.201212  0.081081            0.210526    0.869565
2   0.145292  0.081081            0.157895    0.369565
3   0.000000  0.243243            0.000000    0.326087
4   0.849838  0.513514            1.000000    0.086957
5   0.253363  0.567568            0.263158    0.891304
6   0.532236  0.972973            0.789474    0.913043
7   0.489100  0.621622            0.789474    0.673913
8   0.003798  0.162162            0.000000    0.021739
9   0.786932  0.648649            0.947368    0.021739
10  0.243159  0.648649            0.157895    0.847826
11  0.446255  0.324324            0.421053    0.891304
12  0.083198  0.027027            0.052632    0.760870
13  0.551252  0.621622            1.000000    0.826087
14  1.000000  0.648649            1.000000    0.239130
15  0.609230  0.459459            1.000000    1.000000
16  0.445733  1.000000            0.736842    0.391304
17  0.640770  0.675676            0.368421    0.586957
18  0.015451  0.351351            0.000000    0.000000
19  0.124826  0.216216            0.052632    0.304348

In [9]:
standardisation = StandardScaler()
df_standard = pd.DataFrame(standardisation.fit_transform(df[features]), columns=[features])
print(df_standard)

     Salaire       Age Expérience (années) Taille (cm)
0  -0.973933 -1.529042           -1.005795    0.834676
1  -0.590293 -1.249339           -0.606142    0.962595
2  -0.779707 -1.249339           -0.739359   -0.508481
3  -1.271851 -0.689934           -1.139013   -0.636400
4   1.606778  0.242409            1.392127   -1.339958
5  -0.413643  0.428878           -0.472924    1.026555
6   0.530974  1.827392            0.859256    1.090515
7   0.384863  0.615346            0.859256    0.386957
8  -1.258988 -0.969636           -1.139013   -1.531838
9   1.393699  0.708580            1.258909   -1.531838
10 -0.448207  0.708580           -0.739359    0.898635
11  0.239734 -0.410231           -0.073270    1.026555
12 -0.990037 -1.435808           -1.005795    0.642796
13  0.595389  0.615346            1.392127    0.834676
14  2.115418  0.708580            1.392127   -0.892239
15  0.791775  0.055941            1.392127    1.346354
16  0.237966  1.920626            0.726038   -0.444521
17  0.898609  0.801815           -0.206488    0.131118
18 -1.219514 -0.316997           -1.139013   -1.595797
19 -0.849032 -0.783168           -1.005795   -0.700360

In [11]:
mise_echelle_robuste = RobustScaler()
df_rob = pd.DataFrame(mise_echelle_robuste.fit_transform(df[features]), columns=[features])
print(df_rob)

     Salaire       Age Expérience (années) Taille (cm)
0  -0.581144 -1.090909           -0.338983    0.346154
1  -0.329534 -0.909091           -0.135593    0.423077
2  -0.453761 -0.909091           -0.203390   -0.461538
3  -0.776533 -0.545455           -0.406780   -0.538462
4   1.111412  0.060606            0.881356   -0.961538
5  -0.213679  0.181818           -0.067797    0.461538
6   0.405848  1.090909            0.610169    0.500000
7   0.310021  0.303030            0.610169    0.076923
8  -0.768096 -0.727273           -0.406780   -1.076923
9   0.971664  0.363636            0.813559   -1.076923
10 -0.236347  0.363636           -0.203390    0.384615
11  0.214838 -0.363636            0.135593    0.461538
12 -0.591705 -1.030303           -0.338983    0.230769
13  0.448094  0.303030            0.881356    0.346154
14  1.445003  0.363636            0.881356   -0.692308
15  0.576893 -0.060606            0.881356    0.653846
16  0.213679  1.151515            0.542373   -0.423077
17  0.646960  0.424242            0.067797   -0.076923
18 -0.742208 -0.303030           -0.406780   -1.115385
19 -0.499227 -0.606061           -0.338983   -0.576923

In [13]:
abs_maximale = MaxAbsScaler()
df_abs = pd.DataFrame(abs_maximale.fit_transform(df[features]), columns=[features])
print(df_abs)

     Salaire       Age Expérience (années) Taille (cm)
0   0.523592  0.372881                0.10    0.959184
1   0.582753  0.423729                0.25    0.969388
2   0.553543  0.423729                0.20    0.852041
3   0.477650  0.525424                0.05    0.841837
4   0.921563  0.694915                1.00    0.785714
5   0.609994  0.728814                0.30    0.974490
6   0.755663  0.983051                0.80    0.979592
7   0.733131  0.762712                0.80    0.923469
8   0.479634  0.474576                0.05    0.770408
9   0.888704  0.779661                0.95    0.770408
10  0.604664  0.779661                0.20    0.964286
11  0.710751  0.576271                0.45    0.974490
12  0.521108  0.389831                0.10    0.943878
13  0.765597  0.762712                1.00    0.959184
14  1.000000  0.779661                1.00    0.821429
15  0.795881  0.661017                1.00    1.000000
16  0.710478  1.000000                0.75    0.857143
17  0.812356  0.796610                0.40    0.903061
18  0.485721  0.593220                0.05    0.765306
19  0.542853  0.508475                0.10    0.836735